### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by JoseAVallejo12**
unittest and funcionability done

### CODE REVIEW

**Comment by Esteban1891** [comment]
commit one) = 135929d  > What does this file do 10.dumps, 7.dumps, are they necessary?
file.json > = what does that file do, is it necessary to have it?
models/engine/db_storage.py > already did error handling?
models/engine/file_storage.py > What happens on line 32?
you included the file test_code_review.txt?

**Comment by JoseAVallejo12** [comment]
the file 10 and 7 dump are the sql dump for add information.
file.json ins the file where the filestorage.py save the register in json format.
already did error handling? yes
What happens on line 32? which file 
you included the file test_code_review.txt? not

**Comment by Esteban1891** [comment]
ok plis include the test_code_review.txt?

**Comment by Esteban1891** [comment]
os, you include my user name in review file, and the not have inssues in the code?

**Pull request merged**
